[workspace]
members = [".", "nrf-rpc-codegen", "xtask"]

[workspace.dependencies]
nrf-sim-bridge = { git = "https://github.com/tyler-potyondy/nrf-sim-bridge" }

[package]
name = "nrf-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
minicbor = { version = "0.25", default-features = false }
nrf-rpc-codegen = { path = "nrf-rpc-codegen" }

[dev-dependencies]
serial_test = "3"
embassy-executor = { version = "0.7", features = ["arch-std"] }
embassy-futures = "0.1"
nrf-sim-bridge.workspace = true